package dev.freya02.discord.zstd.ffi; // Generated by jextract

/**
 * {@snippet lang=c :
 * typedef struct ZSTD_inBuffer_s {
 *     const void *src;
 *     size_t size;
 *     size_t pos;
 * } ZSTD_inBuffer
 * }
 */
public class ZSTD_inBuffer extends ZSTD_inBuffer_s {

    ZSTD_inBuffer() {
        // Should not be called directly
    }
}
