package dev.freya02.discord.zstd.ffi; // Generated by jextract

/**
 * {@snippet lang=c :
 * typedef struct ZSTD_outBuffer_s {
 *     void *dst;
 *     size_t size;
 *     size_t pos;
 * } ZSTD_outBuffer
 * }
 */
public class ZSTD_outBuffer extends ZSTD_outBuffer_s {

    ZSTD_outBuffer() {
        // Should not be called directly
    }
}
